DELETE http://localhost:3003/api/blogs/*blogin id tähän*
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFuc2t1IiwiaWQiOiI2MmZmNjQ0MjAxYWM0ODI1YTEyZTNiMjEiLCJpYXQiOjE2NjA5MDUyNjl9.2X5rbIGQrNTqHCI44Avax4ajjWcqQzaQCxSnWa7f57c
